name: post_pagination_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.32.0

dependencies:
  bloc: ^9.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.1.0
  intl: ^0.20.2
  pagination_service:
    path: packages/pagination_service

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
