name: post_pagination_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: 3.24.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^8.0.1
  intl: ^0.19.0
  pagination_service:
    path: packages/pagination_service

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
