name: pagination_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
