name: pagination_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  json_annotation: ^4.10.0

dev_dependencies:
  build_runner: ^2.11.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.12.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0
