name: pagination_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
